language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

notifications:
  slack: $SLACK_KEY
  email: false

script:
  - make ci

matrix:
  allow_failures:
    - go: tip
