language: go

go:
  - "1.9"
  - "1.10"
  - "1.11"
  - "tip"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop


install:
  - make deps

script:
  - make all

matrix:
  allow_failures:
    - go: tip
